# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Message-Simple
version:      0.02
version_from: lib/Log/Message/Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Log::Message:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
